on: [push, repository_dispatch]

env:
  DOTNET_NOLOGO: true

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.READ_PACKAGES_TOKEN }}

      - name: Create a .NET Core console project
        run: dotnet new console

      - name: Add Program.cs
        run: echo 'class Program { static void Main() { Console.WriteLine("Hello!"); } }' > Program.cs

      - name: Install nuget-publish package
        run: dotnet add package nuget-publish

      - name: Run the project
        run: dotnet run
